# Generated by Django 3.2.16 on 2025-06-04 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20250521_1139'),
        ('blog', '0006_alter_comment_author'),
        ('blog', '0006_alter_post_pub_date'),
        ('blog', '0015_auto_20240212_2325'),
    ]

    operations = [
    ]
